### ISSUE TITLE
Add JUnit extension that isolates tests

### ISSUE THREAD

**Issue by jakobbraun** [exasol/test-db-builder-java#46]
Add a JUnit extension that isolates a test case. Isolates mean that all objects that were created during a test will be deleted afterwards.

**Ideas for the API**:
```java
@TestDbBuilder
private static ExasolObjectFactory testDbBuilder = ...;

@Tests
void test(@IsolatedTestDbBuilder ExasolObjectFactory factory){
 factory.createSchema("test");
}
```

or

```java
@TestDbBuilder
private static ExasolObjectFactory testDbBuilder = ...;

@Tests
@WithTestDbCleanup
void test(){
  factory.createSchema("test");
}
```

**Expected behavior**:

* TDB deletes the schema `test` after the test execution.
* Objects created in outside the test (for example in beforeAll) are not neleted

**Comment by redcatbear** [comment]
Stale feature request. Closing. Can be reopened if it becomes relevant again.
