### ISSUE TITLE
Fix the `DatabaseObjectWriter` hierarchy

### ISSUE THREAD

**Issue by chiaradiamarcelo** [exasol/test-db-builder-java#54]
At the moment, we have some members of the [DatabaseObjectWriter](https://github.com/exasol/test-db-builder-java/blob/main/src/main/java/com/exasol/dbbuilder/dialects/DatabaseObjectWriter.java) hierarchy that restrict the features of the super classes, as in
https://github.com/exasol/test-db-builder-java/blob/main/src/main/java/com/exasol/dbbuilder/dialects/postgres/PostgreSqlImmediateDatabaseObjectWriter.java#L33

A class should extend another one if:
   - the subclass is a superclass
   - the subclass can do everything the superclass can
   
Extending a class restricting the super class is usually not a good idea, as it breaks the Liskov substitution principle and will eventually lead to a hierarchy hard to maintain, extend and change.

We should fix this.

**Comment by redcatbear** [comment]
Shelved.
