### ISSUE TITLE
Unify the interface for creating database objects

### ISSUE THREAD

**Issue by chiaradiamarcelo** [exasol/test-db-builder-java#55]
Most of the database objects are instantiated with and `com.exasol.db.Identifier`, as in https://github.com/exasol/test-db-builder-java/blob/main/src/main/java/com/exasol/dbbuilder/dialects/postgres/PostgreSqlUser.java#L18

Some other objects do the same but change the API, as in https://github.com/exasol/test-db-builder-java/blob/main/src/main/java/com/exasol/dbbuilder/dialects/postgres/PostgreSqlSchema.java#L18

This makes the API harder to use. We should unify this.

**Comment by priyank0910** [comment]
@chiaradiamarcelo, @jakobbraun Please let me know if I can pick this issue.
