### ISSUE TITLE
JAVA adapter script builder

### ISSUE THREAD

**Issue by redcatbear** [exasol/test-db-builder-java#7]
## Situation

With the basic implementation we can create all kinds of adapter scripts. But especially for Java adapter scripts, a specialized builder could increase code compactness, readability and user convenience.

## Acceptance Criteria

1. Convenience builder for Java Adapter scripts added.
2. Builder accepts JVM parameters (e.g. for configuring a debugger, profiler or SONAR agent)
3. Builder accepts JAR references
4. Builder accepts mail class reference

**Comment by jakobbraun** [comment]
Mostly covered by #42

**Comment by jakobbraun** [comment]
closing since fully covered
